- name: Apply common to all host groups
  hosts: all
  remote_user: ess
  become: yes

  roles:
    - common

- name: Provision db server
  hosts: dbservers
  remote_user: ess
  become: yes
  vars_files:
    - vars.yml

  roles:
    - db
