# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('players', '0001_initial'),
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPenaltyChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object Id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Content Type')),
            ],
        ),
        migrations.CreateModel(
            name='HockeyPenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('time_in', models.DurationField(verbose_name='Time In')),
                ('time_out', models.DurationField(verbose_name='Time Out')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='games.HockeyGame', verbose_name='Game')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='periods.HockeyPeriod', verbose_name='Period')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='players.HockeyPlayer', verbose_name='Player')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='penalties.GenericPenaltyChoice', verbose_name='Penalty')),
            ],
            options={
                'verbose_name_plural': 'Hockey Penalties',
            },
        ),
        migrations.AlterUniqueTogether(
            name='genericpenaltychoice',
            unique_together=set([('name', 'content_type', 'object_id')]),
        ),
    ]
