# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hockeypenalty',
            options={'verbose_name_plural': 'Hockey Penalties'},
        ),
    ]
