import random

import factory
from factory import django, post_generation

from leagues.models import League
from sports.tests import SportFactory


def random_char():
    return chr(random.randint(97, 122))


class LeagueFactory(django.DjangoModelFactory):
    class Meta:
        model = League
        django_get_or_create = ('name',)

    name = factory.sequence(
            lambda x: 'National Sport {} {} {} {} League'.format(random_char(), random_char(), random_char(), x))
    # abbreviated named is autogenerated via overridden .clean method on the model.
    sport = factory.SubFactory(SportFactory)

    @post_generation
    def full_clean(self, obj, extracted, **kwargs):
        self.full_clean(exclude=['slug', 'abbreviated_name'])
