# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HockeyPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('ot1', 'Overtime 1'), ('ot2', 'Overtime 2'), ('ot3', 'Overtime 3'), ('ot4', 'Overtime 4'), ('ot5', 'Overtime 5'), ('ot6', 'Overtime 6'), ('ot7', 'Overtime 7'), ('ot8', 'Overtime 8'), ('ot9', 'Overtime 9'), ('ot10', 'Overtime 10'), ('so', 'Shootout')], max_length=64, verbose_name='Name')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='games.HockeyGame', verbose_name='Game')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hockeyperiod',
            unique_together=set([('name', 'game')]),
        ),
    ]
