all_deployments_dir: "{{ ansible_env.HOME }}/deployments"
failed_deployments_dir: "{{ all_deployments_dir }}/failed_deployments"

deployment_history_file: "{{ all_deployments_dir }}/history.txt"
max_deployment_dirs: 5

ongoing_deployment: "{{ all_deployments_dir }}/{{ deployment_version|regex_replace('/', '_') }}_{{ ansible_date_time.iso8601_basic_short }}"
venv_path: "{{ ongoing_deployment }}/venv"

sites_dir: "{{ ansible_env.HOME }}/sites"
current_symlink: "{{ sites_dir }}/current"
previous_symlink: "{{ sites_dir }}/previous"
