# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles_mask',
            field=models.SmallIntegerField(default=0, verbose_name='Roles Mask'),
        ),
    ]
