# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20170405_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=128, verbose_name='Gender'),
        ),
    ]
