# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20160728_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesmask',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is Complete'),
        ),
    ]
