# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20160729_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesmask',
            name='are_roles_set',
            field=models.BooleanField(default=False, verbose_name='Are Roles Set'),
        ),
    ]
