# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_rolesmask_are_roles_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolesmask',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='rolesmask',
            name='are_objects_created',
            field=models.BooleanField(default=False, verbose_name='Objects Created'),
        ),
    ]
