# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0006_auto_20160730_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolesmask',
            old_name='are_objects_created',
            new_name='are_role_objects_created',
        ),
    ]
