# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_auto_20160730_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesmask',
            name='are_role_objects_created',
            field=models.BooleanField(default=False, verbose_name='Role Objects Created'),
        ),
    ]
