# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0009_remove_userprofile_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='roles_mask',
        ),
    ]
