# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0010_remove_userprofile_roles_mask'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolesmask',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='rolesmask',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='rolesmask',
            name='user',
        ),
        migrations.DeleteModel(
            name='RolesMask',
        ),
    ]
