import factory
import factory.fuzzy
from factory.django import DjangoModelFactory
from factory import post_generation

from sports.models import Sport


class SportFactory(DjangoModelFactory):
    class Meta:
        model = Sport

    name = factory.sequence(lambda x: 'sport {x}'.format(x=x))
    # slug is autogenerated via overridden .clean() method on the model
    description = factory.fuzzy.FuzzyText(length=32)

    @post_generation
    def full_clean(self, obj, extracted, **kwargs):
        self.full_clean(exclude=['slug'])
