import factory
from factory import post_generation, fuzzy, django

from sports.models import Sport


class SportFactory(django.DjangoModelFactory):
    class Meta:
        model = Sport

    name = factory.sequence(lambda x: 'sport {x}'.format(x=x))
    # slug is autogenerated via overridden .clean() method on the model
    description = fuzzy.FuzzyText(length=32)

    @post_generation
    def full_clean(self, obj, extracted, **kwargs):
        self.full_clean(exclude=['slug'])
