import factory
from factory import post_generation, django, Faker

from sports.models import Sport


class SportFactory(django.DjangoModelFactory):
    name = factory.sequence(lambda x: 'sport {x}'.format(x=x))
    # slug is autogenerated via overridden .clean() method on the model
    description = Faker('text', max_nb_chars=32)

    @post_generation
    def full_clean(self, obj, extracted, **kwargs):
        self.full_clean(exclude=['slug'])

    class Meta:
        model = Sport
        django_get_or_create = ('name',)
