# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseballGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=255, verbose_name='Status')),
                ('start', models.DateTimeField(verbose_name='Game Start')),
                ('end', models.DateTimeField(verbose_name='Game End')),
                ('timezone', models.CharField(choices=[('US/Alaska', 'US/Alaska'), ('US/Arizona', 'US/Arizona'), ('US/Central', 'US/Central'), ('US/Eastern', 'US/Eastern'), ('US/Hawaii', 'US/Hawaii'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific'), ('UTC', 'UTC')], max_length=128, verbose_name='Timezone')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HockeyAssist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='HockeyGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=255, verbose_name='Status')),
                ('start', models.DateTimeField(verbose_name='Game Start')),
                ('end', models.DateTimeField(verbose_name='Game End')),
                ('timezone', models.CharField(choices=[('US/Alaska', 'US/Alaska'), ('US/Arizona', 'US/Arizona'), ('US/Central', 'US/Central'), ('US/Eastern', 'US/Eastern'), ('US/Hawaii', 'US/Hawaii'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific'), ('UTC', 'UTC')], max_length=128, verbose_name='Timezone')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HockeyGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(verbose_name='Time')),
                ('type', models.CharField(choices=[('e', 'Even Strength'), ('pp', 'Power play'), ('sh', 'Shorthanded')], max_length=255, verbose_name='Type')),
                ('empty_net', models.BooleanField(default=False, verbose_name='Empty Net')),
                ('value', models.PositiveSmallIntegerField(choices=[(1, '1')], default=1, verbose_name='Value')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='games.HockeyGame', verbose_name='Game')),
            ],
        ),
    ]
