# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('penalties', '0001_initial'),
        ('common', '0002_auto_20171202_0346'),
        ('periods', '0001_initial'),
        ('players', '0004_auto_20170616_0220'),
        ('games', '0001_initial'),
        ('seasons', '0005_auto_20171024_0042'),
        ('locations', '0003_auto_20171014_0012'),
        ('teams', '0003_team_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='hockeygoal',
            name='penalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='penalties.HockeyPenalty', verbose_name='Penalty'),
        ),
        migrations.AddField(
            model_name='hockeygoal',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='periods.HockeyPeriod', verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='hockeygoal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='players.HockeyPlayer', verbose_name='Player'),
        ),
        migrations.AddField(
            model_name='hockeygame',
            name='away_players',
            field=models.ManyToManyField(related_name='away_games', to='players.HockeyPlayer', verbose_name='Away Roster'),
        ),
        migrations.AddField(
            model_name='hockeygame',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='teams.Team', verbose_name='Away Team'),
        ),
        migrations.AddField(
            model_name='hockeygame',
            name='home_players',
            field=models.ManyToManyField(related_name='home_games', to='players.HockeyPlayer', verbose_name='Home Roster'),
        ),
        migrations.AddField(
            model_name='hockeygame',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='teams.Team', verbose_name='Home Team'),
        ),
        migrations.AddField(
            model_name='hockeygame',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='locations.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='hockeygame',
            name='point_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.GenericChoice', verbose_name='Point Value'),
        ),
        migrations.AddField(
            model_name='hockeygame',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='seasons.Season', verbose_name='Season'),
        ),
        migrations.AddField(
            model_name='hockeygame',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.GenericChoice', verbose_name='Game Type'),
        ),
        migrations.AddField(
            model_name='hockeyassist',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assists', to='games.HockeyGoal', verbose_name='Goal'),
        ),
        migrations.AddField(
            model_name='hockeyassist',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assists', to='players.HockeyPlayer', verbose_name='Player'),
        ),
    ]
