# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20171208_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hockeygoal',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='games.HockeyGame', verbose_name='Game'),
        ),
    ]
