# Generated by Django 2.2.13 on 2020-06-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20180219_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseballgame',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='scheduled', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='hockeygame',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='scheduled', max_length=255, verbose_name='Status'),
        ),
    ]
