# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20170616_0220'),
        ('games', '0003_auto_20171209_0151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hockeyassist',
            unique_together=set([('player', 'goal')]),
        ),
    ]
