# Generated by Django 2.2.15 on 2020-08-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200618_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseballgame',
            old_name='away_players',
            new_name='away_players_old',
        ),
        migrations.RenameField(
            model_name='baseballgame',
            old_name='home_players',
            new_name='home_players_old',
        ),
        migrations.RenameField(
            model_name='hockeygame',
            old_name='away_players',
            new_name='away_players_old',
        ),
        migrations.RenameField(
            model_name='hockeygame',
            old_name='home_players',
            new_name='home_players_old',
        ),
    ]
