# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20171209_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hockeygoal',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(1, '1')], default=1, verbose_name='Value'),
        ),
    ]
