# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20171218_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hockeygame',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=255, verbose_name='Status'),
        ),
    ]
