# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 03:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_team_and_created_by(apps, schema_editor):
    HockeyGame = apps.get_model('games', 'HockeyGame')
    Manager = apps.get_model('managers', 'Manager')
    User = apps.get_model('auth', 'User')
    for game in HockeyGame.objects.all():
        managers = [m for m in Manager.objects.filter(team=game.home_team) if m.is_active]
        game.team = game.home_team
        try:
            game.created_by = managers[0].user
        except IndexError:
            game.created_by = User.objects.filter(is_superuser=True).first()
        game.save()


def unset_team_and_created_by(apps, schema_editor):
    HockeyGame = apps.get_model('games', 'HockeyGame')
    for game in HockeyGame.objects.all():
        game.team = None
        game.created_by = None
        game.save()


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_locations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0007_auto_20171225_1928'),
        ('managers', '0002_auto_20170417_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='hockeygame',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='hockeygame',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.Team', verbose_name='Team'),
        ),
        migrations.RunPython(set_team_and_created_by, unset_team_and_created_by),
    ]
