# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_locations'),
        ('locations', '0006_auto_20180112_0303'),
        ('players', '0004_auto_20170616_0220'),
        ('seasons', '0005_auto_20171024_0042'),
        ('common', '0003_genericchoice_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0008_auto_20180112_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseballGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=255, verbose_name='Status')),
                ('start', models.DateTimeField(verbose_name='Game Start')),
                ('end', models.DateTimeField(verbose_name='Game End')),
                ('timezone', models.CharField(choices=[('US/Alaska', 'US/Alaska'), ('US/Arizona', 'US/Arizona'), ('US/Central', 'US/Central'), ('US/Eastern', 'US/Eastern'), ('US/Hawaii', 'US/Hawaii'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific'), ('UTC', 'UTC')], max_length=128, verbose_name='Timezone')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('away_players', models.ManyToManyField(related_name='away_games', to='players.BaseballPlayer', verbose_name='Away Roster')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_baseballgames', to='teams.Team', verbose_name='Away Team')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baseballgames_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('home_players', models.ManyToManyField(related_name='home_games', to='players.BaseballPlayer', verbose_name='Home Roster')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_baseballgames', to='teams.Team', verbose_name='Home Team')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseballgames', to='locations.Location', verbose_name='Location')),
                ('point_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.GenericChoice', verbose_name='Point Value')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseballgames', to='seasons.Season', verbose_name='Season')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.Team', verbose_name='Team')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.GenericChoice', verbose_name='Game Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='hockeygame',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_hockeygames', to='teams.Team', verbose_name='Away Team'),
        ),
        migrations.AlterField(
            model_name='hockeygame',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hockeygames_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='hockeygame',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_hockeygames', to='teams.Team', verbose_name='Home Team'),
        ),
        migrations.AlterField(
            model_name='hockeygame',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hockeygames', to='locations.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='hockeygame',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hockeygames', to='seasons.Season', verbose_name='Season'),
        ),
    ]
