-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 4c90c9557da7c0d695d6a729bae8b1de4e496cbf
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer
