-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: flake8
