-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 7539d8bd1a00a3c1bfd34cdb606d3a6372e83469
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: flake8
