repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v1.2.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: flake8
