-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 3fa02652357ff0dbb42b5bc78c673b7bc105fcf3
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer
