repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v1.2.3
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: flake8
