-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 4ef03c4223ad322c7adaa6c6c0efb26b57df3b71
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer
