repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.5
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: flake8
