language: python

cache:
  pip: true
  directories:
    - node_modules

python:
  - "3.6"

install:
  - source $HOME/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
  - pip install -r requirements.txt
  - npm install
  - npm run build

env:
#  matrix:
#    - TEST_SUITE=unit
#    - TEST_SUITE=accept

  global:
    - DJANGO_SETTINGS_MODULE="escoresheet.settings.settings"
    - TRAVIS_NODE_VERSION="6"

script:
  - bash run_tests.sh # $TEST_SUITE

git:
  depth: 10

branches:
  only:
    - master
    - dev

notifications:
  email:
    on_success: change
    on_failure: always
