language: python

cache:
  pip: true
  directories:
    - node_modules

python:
  - "3.6"

addons:
  chrome: stable
  # firefox: latest

install:
  - source $HOME/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
  - pip install -r requirements.txt
  - npm install
  - npm run build

env:
  global:
    - DJANGO_SETTINGS_MODULE="ayrabo.settings.settings"
    - TRAVIS_NODE_VERSION="8"

script:
  - bash run_tests.sh

git:
  depth: 5

notifications:
  email:
    on_success: change
    on_failure: always
