language: python

cache: pip

python:
  - "3.5.2"

install:
  - pip install -r requirements.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE="escoresheet.settings.settings"

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

script:
  - python manage.py test apps/
  - python manage.py behave features/

branches:
  only:
    - master
    - dev

notifications:
  email:
    on_success: change
    on_failure: always
