language: python

cache: pip

sudo: required

python:
  - "3.4"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install node -y
  - sudo npm -g install phantomjs-prebuilt

install:
  - pip install -r requirements.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE="escoresheet.settings.settings"

script:
  - python manage.py test apps/
  - python manage.py behave features/

branches:
  only:
    - master
    - dev

notifications:
  email:
    on_success: change
    on_failure: always
