language: python

cache: pip

python:
  - "3.5"

install:
  - pip install -r requirements.txt

env:
  global:
    - DJANGO_SETTINGS_MODULE="escoresheet.settings.settings"

script:
  - bash run_tests.sh

branches:
  only:
    - master
    - dev

notifications:
  email:
    on_success: change
    on_failure: always
