language: python

cache:
  pip: true
  directories:
    - node_modules

python:
  - "3.6"

addons:
  chrome: stable
  # firefox: latest

services:
  - docker

env:
  global:
    - TRAVIS_NODE_VERSION="8"
    - DOCKER_COMPOSE_VERSION="1.24.0"

before_install:
  - sudo service postgresql stop
  - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - source $HOME/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION

install:
  - echo "POSTGRES_PASSWORD=myweakpassword" >> .env
  - echo "POSTGRES_USER=ayrabo" >> .env
  - echo "POSTGRES_DB=ayrabo" >> .env
  - echo "POSTGRES_HOST=localhost" >> .env
  - echo "POSTGRES_PORT=5432" >> .env
  - docker-compose up --build --quiet-pull -d postgres
  - pip install -r requirements.txt
  - npm install
  - npm run build

script:
  - bash run_tests.sh

git:
  depth: 5

branches:
  only:
    - master
    - dev

notifications:
  email:
    on_success: change
    on_failure: always
