version: '3.7'

services:
  postgres:
    build: devops/docker/postgres
    image: ayrabo/postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
