version: '3.3'

services:
  postgres:
    build: postgres/
    image: ayrabo/postgres
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    volumes:
      - ayrabopgdata:/var/lib/postgresql/data
volumes:
  ayrabopgdata:
