version: '3'

services:
  postgres:
    build: postgres/
    image: ess/postgres
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/ess/postgresql/data:/var/lib/postgresql/data
