import random

from factory import Faker, SubFactory, django, post_generation, sequence

from leagues.models import League
from sports.tests import SportFactory


def random_char():
    return chr(random.randint(97, 122))


class LeagueFactory(django.DjangoModelFactory):
    name = sequence(
        lambda x: 'National Sport {} {} {} {} League'.format(random_char(), random_char(), random_char(), x))
    # abbreviated name is autogenerated via overridden .clean method on the model.
    sport = SubFactory(SportFactory)
    website = Faker('url')

    class Meta:
        model = League
        django_get_or_create = ('name',)

    @post_generation
    def full_clean(self, obj, extracted, **kwargs):
        self.full_clean(exclude=['slug', 'abbreviated_name'])
