# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportregistration',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Registration Complete'),
        ),
    ]
