# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20180429_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
