# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0003_auto_20180527_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportregistration',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('coach', 'Coach'), ('referee', 'Referee'), ('manager', 'Manager'), ('scorekeeper', 'Scorekeeper')], db_index=True, max_length=64, null=True, verbose_name='Role'),
        ),
        migrations.AlterUniqueTogether(
            name='sportregistration',
            unique_together=set([('user', 'sport', 'role')]),
        ),
    ]
