# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 01:53
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    SportRegistration = apps.get_model('sports', 'SportRegistration')

    def get_roles(roles_mask):
        ROLES = ['Player', 'Coach', 'Referee', 'Manager', 'Scorekeeper']
        return [r for r in ROLES if (roles_mask & 2 ** ROLES.index(r)) != 0]

    for sr in SportRegistration.objects.all():
        user = sr.user
        sport = sr.sport
        roles = get_roles(sr.roles_mask)
        for role in roles:
            role_choice = role.lower()
            SportRegistration.objects.create(user=user, sport=sport, role=role_choice)


def reverse_func(apps, schema_editor):
    SportRegistration = apps.get_model('sports', 'SportRegistration')

    SportRegistration.objects.exclude(role=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('sports', '0004_auto_20180710_0153'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=reverse_func),
    ]
