# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 02:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_auto_20180710_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportregistration',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sport_registrations', to='sports.Sport', verbose_name='Sport'),
        ),
        migrations.AlterField(
            model_name='sportregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sport_registrations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
