# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 00:34
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    SportRegistration = apps.get_model('sports', 'SportRegistration')
    SportRegistration.objects.filter(role=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_auto_20180710_0242'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sportregistration',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('coach', 'Coach'), ('referee', 'Referee'), ('manager', 'Manager'), ('scorekeeper', 'Scorekeeper')], db_index=True, max_length=64, verbose_name='Role'),
        ),
        migrations.RemoveField(
            model_name='sportregistration',
            name='roles_mask',
        ),
    ]
