- import_role:
    name: postgres

- name: Install postgres server
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-9.6
    - libpq-dev

- name: Install psycopg2 for ansible
  pip:
    name: psycopg2
    state: present

- name: Remove default postgres timezone setting
  lineinfile:
    path: "/etc/postgresql/9.6/main/postgresql.conf"
    regexp: "^timezone = 'localtime'$"
    state: absent

- name: Configure timezone for postgres
  lineinfile:
    path: "/etc/postgresql/9.6/main/postgresql.conf"
    insertafter: EOF
    line: "timezone = 'UTC'"
    state: present

- name: Configure listen addresses for postgres
  lineinfile:
    path: "/etc/postgresql/9.6/main/postgresql.conf"
    insertafter: EOF
    line: "listen_addresses = '0.0.0.0, ::'"
    state: present

- name: Allow {{ db_user }} to connect to postgres
  lineinfile:
    path: "/etc/postgresql/9.6/main/pg_hba.conf"
    insertafter: EOF
    line: "host  {{ db_name }}  {{ db_user }} {{ item }}  md5"
    state: present
  with_items:
    - "0.0.0.0/0"
    - "::0/0"

- name: Restart postgres
  service:
    name: postgresql
    state: restarted

- name: Create {{ db_user }} user
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    encrypted: yes
    state: present

- name: Create {{ db_name }} database
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    encoding: "{{ db_encoding }}"
    owner: "{{ db_user }}"
    state: present

- name: Configure role attributes for {{ db_user }}
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    db: "{{ db_name }}"
    role_attr_flags: CREATEDB
    state: present
