- import_role:
    name: nodejs

- import_role:
    name: nginx

- name: Copy global nginx config
  become: yes
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"

- name: Create server config {{ ansible_default_ipv4.address }}
  become: yes
  template:
    src: "server_boilerplate.j2"
    dest: "/etc/nginx/sites-available/{{ ansible_default_ipv4.address }}"

- name: Enable server config for {{ ansible_default_ipv4.address }}
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ ansible_default_ipv4.address }}"
    dest: "/etc/nginx/sites-enabled/{{ ansible_default_ipv4.address }}"
    state: link

- import_tasks: ../../../utils/reload_nginx_conf.yml

- name: Create all deployments directory
  file:
    path: "{{ all_deployments_dir }}"
    state: directory

- name: Create failed deployments directory
  file:
    path: "{{ failed_deployments_dir }}"
    state: directory

- name: Create sites directory
  file:
    path: "{{ sites_dir }}"
    state: directory

- name: Create media directory
  file:
    path: "{{ media_root }}"
    state: directory

- import_tasks: gunicorn.yml
