- name: Add nginx ppa
  become: yes
  apt_repository:
    repo: ppa:nginx/stable
    state: present
    update_cache: yes

- name: Install nginx
  become: yes
  apt:
    name: nginx
    state: present

- name: Remove default enabled site
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy global nginx config
  become: yes
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"

- name: Create server config {{ ansible_default_ipv4.address }}
  become: yes
  template:
    src: "server_boilerplate.j2"
    dest: "/etc/nginx/sites-available/{{ ansible_default_ipv4.address }}"

- name: Enable server config for {{ ansible_default_ipv4.address }}
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ ansible_default_ipv4.address }}"
    dest: "/etc/nginx/sites-enabled/{{ ansible_default_ipv4.address }}"
    state: link

- include_tasks: ../../../utils/reload_nginx_conf.yml

# TODO nginx supervisor
