# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_auto_20170416_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='position',
            field=models.CharField(choices=[('head_coach', 'Head Coach'), ('assistant_coach', 'Assistant Coach')], max_length=255, verbose_name='Position'),
        ),
    ]
