- name: Add git PPA
  apt_repository:
    repo: ppa:git-core/ppa
    state: present

- include: ../../../utils/update_apt_cache.yml

- name: Upgrade system packages
  apt:
    upgrade: dist
    autoremove: yes

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - git
    - vim
    - tmux
    - python3-dev
    - python3-pip
    - python3-virtualenv
    - python-dev
    - python-pip
    - python-virtualenv
    - supervisor

- name: Update pip
  pip:
    name: pip
    state: latest
