#- name: Set static ip
#  template:
#    src: interfaces.j2
#    dest: /etc/network/interfaces
#    backup: yes
#
#- name: Restart networking
#  service:
#    name: networking
#    state: restarted

- name: Add git PPA
  apt_repository:
    repo: ppa:git-core/ppa
    state: present
    update_cache: no

- name: Add python PPA
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
    update_cache: no

- import_tasks: ../../../utils/update_apt_cache.yml

- import_tasks: ../../../utils/dist_upgrade.yml
  vars:
    update_cache: no

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - git
    - vim
    - tmux
    - build-essential
    - python3.6
    - python3.6-dev
    - python3-pip
    - python3.6-venv
    - python-dev
    - python-pip
    - python-virtualenv
    - supervisor
    - htop

- name: Update pip
  pip:
    name: pip
    state: latest
