# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baseballplayer',
            unique_together=set([('user', 'team')]),
        ),
        migrations.AlterUniqueTogether(
            name='basketballplayer',
            unique_together=set([('user', 'team')]),
        ),
        migrations.AlterUniqueTogether(
            name='hockeyplayer',
            unique_together=set([('user', 'team')]),
        ),
    ]
