# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20170417_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hockeyplayer',
            name='position',
            field=models.CharField(choices=[('C', 'Center'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('LD', 'Left Defense'), ('RD', 'Right Defense'), ('G', 'Goaltender')], max_length=255, verbose_name='Position'),
        ),
    ]
