# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 06:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('leagues', '0001_initial'),
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HockeySeasonRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('default', models.BooleanField(default=False, verbose_name='Default Season Roster')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_rosters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('players', models.ManyToManyField(to='players.HockeyPlayer')),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='leagues.League', unique_for_year='start_date')),
                ('teams', models.ManyToManyField(related_name='seasons', to='teams.Team')),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.AddField(
            model_name='hockeyseasonroster',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.Season'),
        ),
        migrations.AddField(
            model_name='hockeyseasonroster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_rosters', to='teams.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set([('end_date', 'league'), ('start_date', 'league')]),
        ),
    ]
