# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League', unique_for_year='start_date')),
                ('teams', models.ManyToManyField(to='teams.Team')),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set([('start_date', 'league'), ('end_date', 'league')]),
        ),
    ]
