# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('players', '0003_auto_20160731_1905'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HockeySeasonRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False, verbose_name='Default Season Roster')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('players', models.ManyToManyField(to='players.HockeyPlayer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
    ]
