# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_hockeyseasonroster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hockeyseasonroster',
            options={'get_latest_by': 'created', 'ordering': ['created']},
        ),
    ]
