# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_auto_20180429_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hockeyseasonroster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='season_rosters', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='hockeyseasonroster',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seasons.Season'),
        ),
        migrations.AlterField(
            model_name='hockeyseasonroster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_rosters', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='season',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='leagues.League', unique_for_year='start_date'),
        ),
    ]
