# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_auto_20170221_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(related_name='seasons', to='teams.Team'),
        ),
    ]
