# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_auto_20170221_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='leagues.League', unique_for_year='start_date'),
        ),
    ]
