# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 04:46
from __future__ import unicode_literals

from django.db import migrations, models


def forward_func(apps, schema_editor):
    HockeySeasonRoster = apps.get_model('seasons', 'HockeySeasonRoster')
    for roster in HockeySeasonRoster.objects.all():
        if not roster.name:
            roster.name = 'Season Roster {}'.format(roster.id)
            roster.save()


def reverse_func(apps, schema_editor):
    HockeySeasonRoster = apps.get_model('seasons', 'HockeySeasonRoster')
    for roster in HockeySeasonRoster.objects.all():
        if roster.name.startswith('Season Roster'):
            roster.name = ''
            roster.save()


class Migration(migrations.Migration):
    dependencies = [
        ('seasons', '0005_auto_20171024_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hockeyseasonroster',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.RunPython(forward_func, reverse_func),
    ]
