# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_manager_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
