# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlocation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='teamlocation',
            unique_together=set([('team', 'location')]),
        ),
    ]
