# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20171013_0316'),
        ('locations', '0002_auto_20171013_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary Location')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teamlocation',
            unique_together=set([('team', 'location')]),
        ),
    ]
