# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20180219_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='teamlocation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.Team'),
        ),
    ]
