# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 03:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20180107_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid phone number.', regex=re.compile('^\\(?[2-9]\\d{2}\\)? \\d{3}-\\d{4}$', 32))], verbose_name='Phone Number'),
        ),
    ]
