# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericModelChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object Id')),
                ('short_name', models.CharField(help_text='The value stored in the database', max_length=255, verbose_name='Short Name')),
                ('long_name', models.CharField(help_text='The value shown to users', max_length=255, verbose_name='Long Name')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Content Type')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='genericmodelchoice',
            unique_together=set([('short_name', 'content_type', 'object_id')]),
        ),
    ]
