# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20171202_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericchoice',
            name='type',
            field=models.CharField(choices=[('game_type', 'Game Type'), ('game_point_value', 'Game Point Value')], default='', max_length=255, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
