# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180527_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin')], db_index=True, max_length=255, verbose_name='Name'),
        ),
    ]
