# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='full_name',
            field=models.CharField(error_messages={'unique': 'League with this name already exists'}, max_length=256, verbose_name='Full Name'),
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together=set([('full_name', 'sport')]),
        ),
    ]
