# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20160701_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together=set([('full_name', 'sport'), ('slug', 'sport')]),
        ),
    ]
