# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20180527_2104'),
    ]

    operations = [
        migrations.RenameField('league', 'full_name', 'name'),
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(error_messages={'unique': 'League with this name already exists'}, max_length=255,
                                   verbose_name='Name'),
        ),
    ]
