# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20160706_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 26, 22, 24, 6, 855572), verbose_name='Created'),
            preserve_default=False,
        ),
    ]
