# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 02:37
from __future__ import unicode_literals

import ayrabo.utils.utils
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20181013_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=ayrabo.utils.utils.UploadTo('leagues/logos/'), verbose_name='Logo'),
        ),
    ]
