# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 01:42
from __future__ import unicode_literals

import ayrabo.utils.model_fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_league_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='website',
            field=ayrabo.utils.model_fields.WebsiteField(blank=True, help_text='Make sure to include http:// or https://', max_length=255, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Website'),
        ),
    ]
