# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_league_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.Sport', verbose_name='Sport'),
        ),
    ]
