#- name: Remove existing docker packages
#  become: yes
#  apt:
#    name: "{{ item }}"
#    state: absent
#  with_items:
#    - docker
#    - docker-engine

- name: Update/upgrade system dependencies
  become: yes
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
    - python-pip
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - git
    - vim

- include: ../../web/tasks/nodejs.yml

- name: Add docker apt key
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add docker apt repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: yes
    state: present

- name: Install docker-ce
  become: yes
  apt:
    name: docker-ce
    state: present

- name: Add docker group
  become: yes
  group:
    name: docker
    state: present

- name: Add user to docker group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    append: yes
    createhome: no
    groups: docker

- name: Update pip
  become: yes
  pip:
    name: pip
    state: latest

- name: Install docker compose
  become: yes
  pip:
    name: docker-compose
    state: present

- name: Reboot
  become: yes
  shell: reboot
