- import_role:
    name: postgres

- import_tasks: ../../../utils/dist_upgrade.yml
  vars:
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3.6
    - python3.6-dev
    - python3.6-venv
    - python3-pip
    - python
    - python-dev
    - python-pip
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - git
    - vim
    - postgresql-client-9.6

- import_role:
    name: nodejs

- name: Update pip
  pip:
    name: pip
    state: latest

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-compose==1.21.0
    - PyYAML
    - virtualenv
