- include_tasks: ../../db/tasks/add_postgres_apt.yml

- name: Update/upgrade system dependencies
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3.6
    - python3.6-dev
    - python3.6-venv
    - python3-pip
    - python
    - python-dev
    - python-pip
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - git
    - vim
    - postgresql-client-9.6

- include_tasks: ../../web/tasks/nodejs.yml

- name: Update pip
  pip:
    name: pip
    state: latest

- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-compose==1.16.1
    - PyYAML
    - virtualenv
