- name: Copy over .env
  template:
    src: ../../deploy/templates/.env.example.j2
    dest: "{{ project_root }}/.env"

- name: Create venv and install requirements
  pip:
    chdir: "{{ project_root }}"
    virtualenv: "{{ venv_path }}"
    virtualenv_python: "{{ venv_python_version }}"
    state: present
    requirements: "requirements.txt"

# The npm module was only working w/ state: latest after the node v8 update. It doesn't seem like it was actually
# updating the packages to the latest versions but I don't want to take a chance.
- name: Install npm packages
  shell: npm install
  args:
    chdir: "{{ project_root }}"

- name: Install pre-commit
  shell: "source {{ venv_path }}/bin/activate && pre-commit install"
  args:
    chdir: "{{ project_root }}"
    executable: "/bin/bash"

# If getting errors make sure have latest docker-py, docker-compose, PyYAML, docker for pip2 and pip3. Use -U
- name: Build and start docker containers in detached mode (this may take a while)
  shell: "docker-compose up -d"
  args:
    chdir: "{{ project_root }}"
    executable: "/bin/bash"

- name: Wait for postgres container to start up
  pause:
    seconds: 8

- name: Run migrations
  django_manage:
    app_path: "{{ project_root }}"
    command: "migrate --noinput"
    virtualenv: "{{ venv_path }}"

- name: Run seeds
  django_manage:
    app_path: "{{ project_root }}"
    command: "seed"
    virtualenv: "{{ venv_path }}"

# Don't use ansible to run the test suite because the user should really see all stdout while the tests are running.
