- name: Deploy code to webserver
  hosts: webservers
  remote_user: ayrabo
  vars_prompt:
    - name: server_type
      prompt: The server type to work with
      private: no

    - name: deployment_version
      prompt: Branch name, SHA hash, release version
      default: master
      private: no
  vars_files:
    - "vars/{{ server_type }}.yml"

  roles:
    - web
    - deploy
    - cron
