- name: Apply common to all host groups
  hosts: all
  remote_user: ayrabo
  become: yes

  roles:
    - common

- name: Provision db server
  hosts: dbservers
  remote_user: ayrabo
  become: yes
  vars_files:
    - "vars/{{ server_type }}.yml"

  roles:
    - db

- import_playbook: deploy.yml
