- name: Apply common to all host groups
  hosts: all
  remote_user: ess
  become: yes

  roles:
    - common

- name: Provision db server
  hosts: dbservers
  remote_user: ess
  become: yes
  vars_files:
    - "{{ server_type }}_vars.yml"

  roles:
    - db

- name: Provision web server and deploy code
  hosts: webservers
  remote_user: ess
  vars_prompt:
    - name: server_type
      prompt: The server type to work with
      private: no

    - name: deployment_version
      prompt: Branch name, SHA hash, release version
      default: master
      private: no
  vars_files:
    - "{{ server_type }}_vars.yml"
    - "roles/deploy/vars/main.yml"

  roles:
    - web
    - deploy
