# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20160706_0031'),
        ('referees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
                model_name='referee',
                old_name='division',
                new_name='league',
        ),
        migrations.AlterField(
            model_name='referee',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
        ),
        migrations.AlterUniqueTogether(
            name='referee',
            unique_together=set([('user', 'league')]),
        ),
    ]
