# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0002_referee_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.League'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referees', to=settings.AUTH_USER_MODEL),
        ),
    ]
