# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0002_referee_created'),
        ('referees', '0002_auto_20160727_0012'),
    ]

    operations = [
    ]
