# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('website', models.URLField(blank=True, help_text='You must include http:// or https://', max_length=255, null=True, verbose_name='Website')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.Division')),
            ],
            options={
                'ordering': ['name', 'division'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('slug', 'division'), ('name', 'division')]),
        ),
    ]
