# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 06:42
from __future__ import unicode_literals

import ayrabo.utils.model_fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisions', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('website', ayrabo.utils.model_fields.WebsiteField(blank=True, help_text='Make sure to include http:// or https://', max_length=255, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Website')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisions.Division')),
                ('locations', models.ManyToManyField(related_name='teams', through='locations.TeamLocation', to='locations.Location', verbose_name='Locations')),
            ],
            options={
                'ordering': ['name', 'division'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('name', 'division'), ('slug', 'division')]),
        ),
    ]
