# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 03:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import escoresheet.utils.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='website',
            field=escoresheet.utils.model_fields.WebsiteField(blank=True, default='', help_text='Make sure to include http:// or https://', max_length=255, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Website'),
            preserve_default=False,
        ),
    ]
