# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('slug', 'division'), ('name', 'division')]),
        ),
    ]
