# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
