# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20171014_0012'),
        ('teams', '0002_auto_20171013_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='locations',
            field=models.ManyToManyField(related_name='teams', through='locations.TeamLocation', to='locations.Location', verbose_name='Locations'),
        ),
    ]
