# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def forwards_func(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    Organization = apps.get_model('organizations', 'Organization')

    for team in Team.objects.all():
        try:
            organization = Organization.objects.get(name=team.name)
        except Organization.DoesNotExist:
            # Generating the slug via full_clean(exclude=['slug']) doesn't work. Looks like model functions
            # aren't available in RunPython
            organization = Organization.objects.create(name=team.name, slug=slugify(team.name))

        team.organization = organization
        team.save()


def reverse_func(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    Team = apps.get_model('teams', 'Team')

    for team in Team.objects.all():
        team.organization = None
        team.save()

    # Deleted after the loop so the organization FK on Team doesn't raise exceptions on_delete
    Organization.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('teams', '0003_team_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='organizations.Organization', verbose_name='Organization'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='organizations.Organization', verbose_name='Organization'),
        ),
    ]
