# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20181031_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='divisions.Division', verbose_name='Division'),
        ),
    ]
