# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set([('name', 'league')]),
        ),
    ]
