# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0002_auto_20160627_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set([('name', 'league'), ('slug', 'league')]),
        ),
    ]
