# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0003_auto_20180527_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='leagues.League', verbose_name='League'),
        ),
    ]
