# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    organizations = Organization.objects.all().prefetch_related('teams__division__league__sport')
    for o in organizations:
        teams = o.teams.all()
        # Just use the first team, I'm 99% sure all of the teams are in the same sport.
        o.sport = teams.first().division.league.sport
        o.save()


def reverse_func(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    organizations = Organization.objects.all()
    for o in organizations:
        o.sport = None
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_auto_20180710_0242'),
        ('organizations', '0002_auto_20180527_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='sports.Sport', verbose_name='Sport'),
        ),
        migrations.RunPython(forwards_func, reverse_code=reverse_func),
        migrations.AlterField(
            model_name='organization',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='sports.Sport', verbose_name='Sport'),
        ),
    ]
